

# 포트 설정
server:
  port: 9590

# db & jsp설정
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://${MYSQL_ADDR}:${MYSQL_PORT}/${MYSQL_DB}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp


# mybatis mapper
mybatis:
  configuration:
    multiple-result-sets-enabled: false
    map-underscore-to-camel-case: true 
    call-setters-on-nulls: true  
    jdbc-type-for-null: varchar 
    default-fetch-size: 500
  mapper-locations: classpath*:mybatis/mapper/**/**.xml


# 로그 관련 설정
logging:
  level:
    jdbc:
      sqlonly: off
      sqltiming: debug
      resultset: off
      resultsettable: debug
      audit: off
      connection: off

jwt:
  header: Authorization
  secret: ${JWT_SECRET}
  accessTokenValidityInSeconds: ${JWT_TOKEN_VIS}
  
    